Repository LedgerProject/eschooltul_backend, pull requests merged in 2021-03, with the labels that each got.

#1 Rubocop fixed
  app/controllers/grades_controller.rb
Labels: bug

#3 PDF content and hash (unique) into Database
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/validator.scss
  app/controllers/grades_controller.rb
  app/controllers/report_controller.rb
  app/controllers/validators_controller.rb
  app/helpers/validator_helper.rb
  app/javascript/components/grades/utils/convertToCSV.js
  app/models/course.rb
  app/models/report.rb
  app/models/student.rb
  app/views/devise/sessions/new.html.erb
  app/views/validators/new.html.erb
  config/routes.rb
  db/migrate/20210310083423_create_reports.rb
  db/migrate/20210315113005_add_student_to_reports.rb
  db/migrate/20210315114318_rename_column_report.rb
  db/migrate/20210316084445_add_course_to_reports.rb
  db/migrate/20210316111310_change_report_content_from_string_to_text.rb
  db/migrate/20210316144656_add_unique_index_report.rb
  db/migrate/20210316155746_index_uniqueness_reports.rb
  db/migrate/20210318081502_change_transaction_id_to_string.rb
  db/schema.rb
  public/javascripts/translations.js
  spec/cassettes/Reports/Grades_show/creates_report.yml
  spec/cassettes/Validators/_create/validates_with_blockchain.yml
  spec/factories/marks.rb
  spec/factories/reports.rb
  spec/fixtures/files/report-in-blockchain.pdf
  spec/helpers/validator_helper_spec.rb
  spec/models/report_spec.rb
  spec/requests/report_request_spec.rb
  spec/requests/validator_request_spec.rb
  spec/support/vcr.rb
Labels: requested-changes

#4 Writting and reading done. Some files removed
  Gemfile.lock
  app/assets/stylesheets/validator.scss
  app/controllers/grades_controller.rb
  app/controllers/validators_controller.rb
  app/helpers/validator_helper.rb
  app/views/validators/new.html.erb
  spec/cassettes/Reports/Grades_show/creates_report.yml
  spec/cassettes/Validators/_create/validates_with_blockchain.yml
  spec/fixtures/files/report-in-blockchain.pdf
  spec/helpers/validator_helper_spec.rb
  spec/requests/validator_request_spec.rb
Labels: approved-for-merge

#5 Code review, changes made
  app/controllers/grades_controller.rb
  app/controllers/report_controller.rb
  app/javascript/components/grades/table/TableRow.jsx
  app/views/report/show.pdf.erb
  config/routes.rb
  spec/cassettes/Reports/Report_create/creates_report.yml
  spec/cassettes/Reports/Report_show/creates_report.yml
  spec/requests/report_request_spec.rb
Labels: approved-for-merge

#6 refactor: 💡 data to csv function
  app/javascript/components/grades/utils/convertToCSV.js
  db/schema.rb
Labels: approved-for-merge

#7 fix(reports): can "regenerate" a report the same day
  app/controllers/report_controller.rb
  app/models/report.rb
  spec/requests/report_request_spec.rb
Labels: approved-for-merge

#8 fix(report): shows school logo in report
  app/views/report/show.pdf.erb
Labels: review-needed

#9 Grades bug solved
  app/controllers/report_controller.rb
  config/locales/en.yml
  config/locales/es.yml
  spec/requests/report_request_spec.rb
Labels: approved-for-merge
